namespace DeadworksManaged.Api;

/// <summary>Collision group that determines which objects interact with each other in the physics simulation.</summary>
public enum CollisionGroup : byte {
	Always = 0,
	Nonphysical,
	Trigger,
	ConditionallySolid,
	FirstUser,
	Default = FirstUser,
	Debris,
	InteractiveDebris,
	Interactive,
	Player,
	BreakableGlass,
	Vehicle,
	PlayerMovement,
	NPC,
	InVehicle,
	Weapon,
	VehicleClip,
	Projectile,
	DoorBlocker,
	PassableDoor,
	Dissolving,
	Pushaway,
	NPCActor,
	NPCScripted,
	PZClip,
	Props,
	LastSharedCollisionGroup,
	// Deadlock collision groups
	CitadelAbilityProjectile = 25,
	CitadelBullet = 26,
	CitadelTimeWarp = 27,
	CitadelBreakableDebris = 28,
	CitadelMinion = 29,
	MaxAllowed = 64,
}
