namespace DeadworksManaged.Api;

/// <summary>Bitmask combining <see cref="InteractionLayer"/> values to specify which content layers a trace interacts with.</summary>
[Flags]
public enum MaskTrace : ulong {
	Empty = 0ul,
	// Base engine layers
	Solid = 1ul << InteractionLayer.ContentsSolid,
	Hitbox = 1ul << InteractionLayer.ContentsHitbox,
	Trigger = 1ul << InteractionLayer.ContentsTrigger,
	Sky = 1ul << InteractionLayer.ContentsSky,
	PlayerClip = 1ul << InteractionLayer.ContentsPlayerClip,
	NpcClip = 1ul << InteractionLayer.ContentsNpcClip,
	BlockLos = 1ul << InteractionLayer.ContentsBlockLos,
	BlockLight = 1ul << InteractionLayer.ContentsBlockLight,
	Ladder = 1ul << InteractionLayer.ContentsLadder,
	Pickup = 1ul << InteractionLayer.ContentsPickup,
	BlockSound = 1ul << InteractionLayer.ContentsBlockSound,
	NoDraw = 1ul << InteractionLayer.ContentsNoDraw,
	Window = 1ul << InteractionLayer.ContentsWindow,
	PassBullets = 1ul << InteractionLayer.ContentsPassBullets,
	WorldGeometry = 1ul << InteractionLayer.ContentsWorldGeometry,
	Water = 1ul << InteractionLayer.ContentsWater,
	Slime = 1ul << InteractionLayer.ContentsSlime,
	TouchAll = 1ul << InteractionLayer.ContentsTouchAll,
	Player = 1ul << InteractionLayer.ContentsPlayer,
	Npc = 1ul << InteractionLayer.ContentsNpc,
	Debris = 1ul << InteractionLayer.ContentsDebris,
	PhysicsProp = 1ul << InteractionLayer.ContentsPhysicsProp,
	NavIgnore = 1ul << InteractionLayer.ContentsNavIgnore,
	NavLocalIgnore = 1ul << InteractionLayer.ContentsNavLocalIgnore,
	PostProcessingVolume = 1ul << InteractionLayer.ContentsPostProcessingVolume,
	UnusedLayer3 = 1ul << InteractionLayer.ContentsUnusedLayer3,
	CarriedObject = 1ul << InteractionLayer.ContentsCarriedObject,
	Pushaway = 1ul << InteractionLayer.ContentsPushaway,
	ServerEntityOnClient = 1ul << InteractionLayer.ContentsServerEntityOnClient,
	CarriedWeapon = 1ul << InteractionLayer.ContentsCarriedWeapon,
	StaticLevel = 1ul << InteractionLayer.ContentsStaticLevel,
	// Deadlock layers
	CitadelTeamAmber = 1ul << InteractionLayer.CitadelTeamAmber,
	CitadelTeamSapphire = 1ul << InteractionLayer.CitadelTeamSapphire,
	CitadelTeamNeutal = 1ul << InteractionLayer.CitadelTeamNeutal,
	CitadelAbility = 1ul << InteractionLayer.CitadelAbility,
	CitadelBullet = 1ul << InteractionLayer.CitadelBullet,
	CitadelProjectile = 1ul << InteractionLayer.CitadelProjectile,
	CitadelUnitHero = 1ul << InteractionLayer.CitadelUnitHero,
	CitadelUnitTrooper = 1ul << InteractionLayer.CitadelUnitTrooper,
	CitadelUnitNeutral = 1ul << InteractionLayer.CitadelUnitNeutral,
	CitadelUnitBuilding = 1ul << InteractionLayer.CitadelUnitBuilding,
	CitadelUnitProp = 1ul << InteractionLayer.CitadelUnitProp,
	CitadelUnitMinion = 1ul << InteractionLayer.CitadelUnitMinion,
	CitadelUnitBoss = 1ul << InteractionLayer.CitadelUnitBoss,
	CitadelUnitGoldOrb = 1ul << InteractionLayer.CitadelUnitGoldOrb,
	CitadelUnitWorldProp = 1ul << InteractionLayer.CitadelUnitWorldProp,
	CitadelUnitTrophy = 1ul << InteractionLayer.CitadelUnitTrophy,
	CitadelUnitZipline = 1ul << InteractionLayer.CitadelUnitZipline,
	CitadelMantleHidden = 1ul << InteractionLayer.CitadelMantleHidden,
	CitadelObscured = 1ul << InteractionLayer.CitadelObscured,
	CitadelTimeWarp = 1ul << InteractionLayer.CitadelTimeWarp,
	CitadelFoliage = 1ul << InteractionLayer.CitadelFoliage,
	CitadelTransparent = 1ul << InteractionLayer.CitadelTransparent,
	CitadelBlockCamera = 1ul << InteractionLayer.CitadelBlockCamera,
	CitadelMantleable = 1ul << InteractionLayer.CitadelMantleable,
	CitadelWalkable = 1ul << InteractionLayer.CitadelWalkable,
	CitadelTempMovementBlocker = 1ul << InteractionLayer.CitadelTempMovementBlocker,
	CitadelBlockMantle = 1ul << InteractionLayer.CitadelBlockMantle,
	CitadelSkyclip = 1ul << InteractionLayer.CitadelSkyclip,
	CitadelValidPingTarget = 1ul << InteractionLayer.CitadelValidPingTarget,
	CitadelCameraCanPassThrough = 1ul << InteractionLayer.CitadelCameraCanPassThrough,
	CitadelAbilityTrigger = 1ul << InteractionLayer.CitadelAbilityTrigger,
	CitadelPortalTrigger = 1ul << InteractionLayer.CitadelPortalTrigger,
	CitadelPortalEnvironment = 1ul << InteractionLayer.CitadelPortalEnvironment,
}
